### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Carmichaeldb** [AuthiQ/ArkData#3]
Is there a discord or somewhere for support to ask questions about this API? I am looking for something that can be used to get information from the server about players, tribes, status, chat, stats, etc and make it viewable via a server community website. Would this work? i'm new with coding in general and never used C++ before. Only been learning javascript, html, css, and php for about 8 months.

**Comment by fean** [comment]
Hey, this product has sadly been deprecated for a long time. I will mark it as much in the readme.
